### ISSUE TITLE
Update mmap-fixed's ``winapi`` dependency

### ISSUE THREAD

**Issue by vurvdev** [darfink/detour-rs#32]
I apologize in advance as this isn't an issue with this repository exactly, but you don't have a repo dedicated for this.

The dependency ``mmap-fixed`` is doubling my compile time simply because of the dependency on winapi 0.2 (which takes 4x as long to compile in comparison to 0.3), and is now causing warnings from cargo about code that will soon be rejected by Rust..

Would appreciate if the winapi dependency could be updated to 0.3+

**Comment by khang06** [comment]
since this hasn't been updated for 20 days, i decided to just port it over to winapi 0.3 myself

```TOML
[patch.crates-io]
mmap-fixed = { git = "https://github.com/khang06/rust-mmap-fixed-fixed.git", rev = "47116f5" }
```
